brain_two/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todos/', include('todos.urls')),
]

todos/urls.py
from django.urls import path
from . import views

app_name = 'todos'

urlpatterns = [
    path('', views.todo_list_list, name='todo_list_list'),
    path('<int:id>/', views.todo_list_detail, name='todo_list_detail'),
]

todos/models.py
from django.db import models


class TodoList(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class TodoItem(models.Model):
    task = models.CharField(max_length=100)
    due_date = models.DateTimeField(null=True, blank=True)
    is_completed = models.BooleanField(default=False)
    list = models.ForeignKey(TodoList, on_delete=models.CASCADE, related_name='items')

    def __str__(self):
        return self.task

todos/views.py
from django.shortcuts import get_object_or_404, render
from .models import TodoList


def todo_list_list(request):
    todo_lists = TodoList.objects.all()
    context = {'todo_lists': todo_lists}
    return render(request, 'todos/todo_list_list.html', context)


def todo_list_detail(request, id):
    todo_list = get_object_or_404(TodoList, id=id)
    context = {'todo_list': todo_list}
    return render(request, 'todos/todo_list_detail.html', context)

todos/templates/todos/todo_list_list.html
<!DOCTYPE html>
<html>
<head>
    <title>Todo Lists</title>
</head>
<body>
    <main>
        <div>
            <h1>My Lists</h1>
            <table>
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Number of items</th>
                    </tr>
                </thead>
                <tbody>
                    {% for todo_list in todo_lists %}
                    <tr>
                        <td><a href="{% url 'todos:todo_list_detail' todo_list.id %}">{{ todo_list.name }}</a></td>
                        <td>{{ todo_list.items.count }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </main>
</body>
</html>

todos/templates/todos/toto_list_detail.html
<!DOCTYPE html>
<html>
<head>
    <title>Todo List Details</title>
</head>
</html>
<body>
    <main>
        <div>
            <h1>{{ todo_list.name }}</h1>
            <h2>Tasks</h2>
            <table>
                <thead>
                    <tr>
                        <th>Task</th>
                        <th>Due date</th>
                    </tr>
                </thead>
                <tbody>
                    {% for todo_item in todo_list.items.all %}
                    <tr>
                        <td>{{ todo_item.task }}</td>
                        <td>{{ todo_item.due_date }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </main>
</body>